service: dns-query

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dns-servers-table: '${self:provider.stage}-dns-servers'
  dynamodb:
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
      Resource:
        - { "Fn::GetAtt": ["DnsServersTable", "Arn"] }

  environment:
    DNS_SERVERS_TABLE: ${self:custom.dns-servers-table}

# you can add packaging information here
package:
 include:
   - node_modules
   - lambda

functions:
  scraper:
    name: ${self:provider.stage}-scraper
    handler: lambda/scraper/handler.hello
    events:
      - http: ANY /

resources:
  - ${file(infrastructure/dynamo.yaml)}
#   - ${file(infrastructure/s3.yaml)}